### PR TITLE
Added support for console.warn and console.error

### PR DESCRIPTION
**Pull request by vivekannan**
Note that I have changed the script src in example.html so that the changes can be seen. If the request is accepted, the source should be changed to the minified version again.
Edit: Also added autoScroll option and support for panel drag.

### CODE REVIEW

**Comment by chinchang** [comment]
@vivekannan gr8! Can you please open a different PR for each issue. Drag support in different PR, warn/error in different.

**Comment by vivekannan** [comment]
Okay, git noob here. I understand what you are asking for, but I don't know how to do it exactly. I did some googling and learnt that there maybe multiple ways to do it. Do you want me to close this request and soft reset my branch and make smaller requests?

**Comment by chinchang** [comment]
Yes. That should work.

**Comment by vivekannan** [comment]
I am completely lost. Can't decide how to correct this pull request. Can you please point me in the right direction.

**Comment by chinchang** [comment]
You can use cherry-picking. https://nathanhoad.net/how-to-cherry-pick-changes-with-git

**Pull request closed without merging**
